spring.application.name=banking-system-api

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=postgres
spring.datasource.password=1234

logging.level.root=INFO
logging.level.com.example.demo=DEBUG
